[package]
name = "passman"
version = "0.0.0"

[dependencies]
rustc-serialize = "*"
toml = "*"
rand = "*"
openssl = "*"
rpassword = "*"
regex = "*"
regex_macros = "*"

[dependencies.clippy]
git = "https://github.com/Manishearth/rust-clippy"
