[package]
name = "passman"
version = "0.0.0"

[dependencies]
rustc-serialize = "*"

[dependencies.clippy]
git = "https://github.com/Manishearth/rust-clippy"

[dependencies.crypt_vault]
path = "crypt_vault"
