[package]
name = "passman"
version = "0.0.0"

[dependencies]
rustc-serialize = "*"
rpassword = "*"

# [dependencies.clippy]
# git = "https://github.com/Manishearth/rust-clippy"

[dependencies.crypto_vault]
path = "../crypto_vault"
