[package]
name = "crypt_vault"
version = "0.1.0"
authors = ["Zachary Bush <zachary.bush@meraki.net>"]

[dependencies.clippy]
git = "https://github.com/Manishearth/rust-clippy"

[dependencies]
openssl = "*"
rand = "*"
regex = "*"
regex_macros = "*"
rpassword = "*"
rustc-serialize = "*"
